### Configuration

# Adjust terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"

set -s escape-time 0
set -g display-time 4000
set -g bell-action none
set -g history-limit 10000
set -g renumber-windows on
set -g focus-events on

### Key bindings
set -g prefix C-a
unbind C-b
bind C-a send-prefix
unbind m

# Source .tmux.conf as suggested in `man tmux`
bind R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Reuse the current path for new panes and windows
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

# vi-mode configuration
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Letters based navigation
bind ^ select-window -l
bind h select-window -t 0 
bind j select-window -t 1
bind k select-window -t 2
bind l select-window -t 3

### Status bar 
TMUX_IN="#{?client_prefix,1,#{?pane_in_mode,1,#{?pane_synchronized,1,0}}}"
TMUX_BG="#{?client_prefix,blue,#{?pane_in_mode,yellow,#{?pane_synchronized,red,default}}}"
TMUX_FG="#{?$TMUX_IN,black,gray}"
TMUX_HL="#{?$TMUX_IN,black,colour10}" # active window color

set-option -g status-style bg=$TMUX_BG,fg=$TMUX_FG
set-option -g status-justify right

set-option -g status-left " #{session_name} "
set-option -g status-left-length 200
set-option -g status-left-style bg=default,fg=default

set-option -g window-status-format ' #I:#W#{?window_zoomed_flag, 󰊓 ,#{window_flags} }'
set-option -g window-status-style fg=default,bg=default
set-option -g window-status-current-format ' #I:#W#{?window_zoomed_flag, 󰊓 , }'
set-option -g window-status-current-style bg=default,fg=$TMUX_HL
set-option -g window-status-last-style fg=default

set-option -g status-right " "
set-option -g automatic-rename-format  "[#{b;s/#{user}/home/i:pane_current_path}]#{?pane_dead,[dead],}"

# Toggle status bar
bind -T prefix t set-option -g status

### Pluggins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-fzf-url' # URLs fuzzy find

set -g @fzf-url-fzf-options '--tmux center,50%,50% --multi --exit-0 --no-preview'

# Automatic plugin manager installation
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

