# Configuration
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -s escape-time 0
set -g display-time 4000
set -g bell-action none
set -g history-limit 10000
set -g renumber-windows on
set -g focus-events on
set -g prefix C-a

# Source .tmux.conf as suggested in `man tmux`
bind R source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Reuse the current path for new panes and windows
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Turn the mouse on, but without copy mode dragging
set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

# vi-mode configuration
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-on \; send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Letters based navigation
bind ^ select-window -l
bind h select-window -t 0 
bind j select-window -t 1
bind k select-window -t 2
bind l select-window -t 3

# Status bar 
source ~/.tmux/themes/melange.conf 

set -g status-style bg="#{E:@bg-format}",fg="#{E:@fg-format}"
set -g status-justify right
set -g status-left " #{session_name} "
set -g status-left-length 200
set -g window-status-format ' #I:#W#{?window_zoomed_flag, 󰊓 ,#{window_flags} }'
set -g window-status-current-format ' #I:#W#{?window_zoomed_flag, 󰊓 , }'
set -g window-status-current-style bg=default,fg="#{E:@hl-format}"
set -g status-right " "
set -g automatic-rename-format "[#{b;s/#{user}/home/i:pane_current_path}]#{?pane_dead,[dead],}"

# Additional key bindigns
bind t set-option -g status # Toggle status bar
unbind m # Disable marking panes

# Pluggins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-fzf-url' # URLs fuzzy find

set -g @fzf-url-fzf-options '-w 50% -h 50% --multi -0 --no-preview'

# Automatic plugin manager installation
if-shell "[ ! -d ~/.tmux/plugins/tpm ]" {
   run "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
   run "~/.tmux/plugins/tpm/bin/install_plugins" 
}

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

