set -g @bg-format "#{?client_prefix,blue,#{?pane_in_mode,yellow,#{?pane_synchronized,red,default}}}"
set -g @fg-format "#{?client_prefix,black,#{?pane_in_mode,black,#{?pane_synchronized,black,brightblack}}}"
set -g @hl-format "#{?client_prefix,brightwhite,#{?pane_in_mode,black,#{?pane_synchronized,brightwhite,brightgreen}}}"
set -g mode-style fg=black,bg=yellow
set -g message-style fg=black,bg=red
